In [ ]:
# Origin: Homework for Programming Week 5
# Author: Augustin Dao
# Date created: 16/09/2016
# Last modified: 21/09/2016


### Part 1. Built-in functions

In [23]:
x <- c(1,2,5)
x
#?append
x_2 <- append(x, c(0,0,0),after = 1) #adds elements to a vector at the specfified position
x_2

[1] 1 2 5

[1] 1 0 0 0 2 5

In [25]:
c <- c(1:9,0,0,0) #combines all arguments into a single vector
c

[1] 1 2 3 4 5 6 7 8 9 0 0 0

In [45]:
intro <- "hello, my name is"
names <- c("Bob","Greg","John Doe")
n <- length(names)

for(i in 1:n){
   cat(i,intro, names[i]," ", "\n") #combines inputs into a single string and and prints
}

1 hello, my name is Bob   
2 hello, my name is Greg   
3 hello, my name is John Doe   


In [66]:
v_1 <- c(1:9)
v_2 <- c(rep(0,9))
matrix_1 <- matrix(v_1,3,3)
matrix_2 <- matrix(v_2,3,3)
matrix_1
matrix_2

cbind(matrix_1,matrix_2) #combines two matrices into a single one, binding by column

[,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    4    7    0    0    0
[2,]    2    5    8    0    0    0
[3,]    3    6    9    0    0    0

In [69]:
v_3 <- c(1:50)
v_3

v_3_bis <- diff(v_3, 4) #iteration to compute lagged differences within a vector and returns results in a vector
v_3_bis

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

[1] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
[39] 4 4 4 4 4 4 4 4

In [78]:
gl(3, 1, labels = c("State 1","State 2", "State 3")) #creates a control variable with given number of possible states
#not really sure of how/when to use it 

[1] State 1 State 2 State 3
Levels: State 1 State 2 State 3

In [80]:
strings <- c("Hello","my name","is","Joe")
grep("Joe", strings) #looks for a specific pattern in a given array and returns its position
#?grep

[1] 4

In [84]:
vector1 <- c(1,2,3)
vector2 <- c(1:3)
vector3 <- c("hello")
vector4 <- c("hello")

identical(vector1, vector2) #tests if two input arguments are exactly equal
identical(vector3, vector4)
identical(vector1, vector4)

[1] FALSE

[1] TRUE

[1] FALSE

In [88]:
dataset <- c(1:25)
dataset
jitter(dataset, factor = 1) #adds to each observation a random noise value bounded by the factor value


[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

[1]  0.9050084  1.9819309  3.0161947  4.1472573  5.1799792  6.0129264
 [7]  6.8022029  8.0309595  8.8461090  9.8130194 11.1296007 11.9989948
[13] 12.8641707 13.9215323 15.1768755 15.8178969 17.1714780 17.9895354
[19] 19.0449394 20.0042941 21.1419593 21.9177798 23.0922882 23.8436283
[25] 24.9321674

In [99]:
origin <- as.Date("01-01-2016")
today_date <- as.Date("13-10-2016")
julian(date, origin = origin) #return number of days between specified date and origin

[1] 3499
attr(,"origin")
[1] "0001-01-20"

In [102]:
vec_1 <- c(1:9)
vec_2 <- c("Hello","I","am","John","Doe")

length(vec_1)# returns the number of components of a vector
length(vec_2)

[1] 9

[1] 5

In [131]:
ls() #?

[1] "c"          "dataset"    "date"       "end"        "i"         
 [6] "intro"      "list"       "matrix_1"   "matrix_2"   "n"         
[11] "name_paste" "names"      "nth"        "origin"     "paste_2"   
[16] "q"          "quit"       "start"      "strings"    "today_date"
[21] "v_1"        "v_2"        "v_3"        "v_3_bis"    "vec_1"     
[26] "vec_2"      "vect"       "vect_rep"   "vector1"    "vector2"   
[31] "vector3"    "vector4"    "x"          "x_2"

In [106]:
mat.or.vec(6,5) #creates a matrix (or vector depending on number of columns)

[,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0
[6,]    0    0    0

In [119]:
#concatenates with a space vector inputs into a vector of strings
name_paste <- paste(c("My name is"), c("Augustin", "John Doe", "Bill"))
paste_2 <- paste(c("Paste n°"), c(1:5))

paste(paste_2,":", name_paste)

[1] "Paste n° 1 : My name is Augustin" "Paste n° 2 : My name is John Doe"
[3] "Paste n° 3 : My name is Bill"     "Paste n° 4 : My name is Augustin"
[5] "Paste n° 5 : My name is John Doe"

In [120]:
start <- c("hel","bon")
end <- c("lo","jour")

paste0(start, end) #same as paste but without spacings between strings 

[1] "hello"   "bonjour"

In [124]:
list <- c(runif(10, 0, 100))
list

range(list) #returns highest and lowest value of a list

[1] 81.99688 18.83771 49.10705 33.53063 61.97036 62.06747 51.76724 82.78191
 [9] 52.51235 88.46868

[1] 18.83771 88.46868

In [133]:
vect <- c(0:5)
vect_rep <- matrix(rep(vect, 5),6,5) #replicates input value a specified number of times

vect_rep

[,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    1    1    1    1    1
[3,]    2    2    2    2    2
[4,]    3    3    3    3    3
[5,]    4    4    4    4    4
[6,]    5    5    5    5    5

In [138]:
a <- c(1:10)
a
rev(a) #sorts in a reverse way 

[1]  1  2  3  4  5  6  7  8  9 10

[1] 10  9  8  7  6  5  4  3  2  1

In [141]:
b <- seq(from = 1, to = 5, by = 0.5) #generates a sequence of number in specified bounds and step
b

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [146]:
c <- sequence(c(1:5))
#generates sequences using a vector of end points and concatenates them into a single vector
c

[1] 1 1 2 1 2 3 1 2 3 4 1 2 3 4 5

In [149]:
sign(c(-5,1,-4,3)) # returns the sign of each entries of a given vector

[1] -1  1 -1  1

In [153]:
list_1 <- c(3,4,1,-9,NA,0,NA,42,-3)
list_1
sort(list_1, decreasing = FALSE, na.last = TRUE) #orders a given vector in a specified way

[1]  3  4  1 -9 NA  0 NA 42 -3

[1] -9 -3  0  1  3  4 42 NA NA

[1]  3  4  1 -9 NA  0 NA 42 -3

In [157]:
order() #same as sort?

NULL

In [159]:
tolower("HELLO") #translates capital case into lower

[1] "hello"

In [160]:
toupper("hello") #converts lower to capital case

[1] "HELLO"

In [165]:
p <- c(1,1,1,1,1,3)
mat <- matrix(rep(p,3),6,3)
p
mat

unique(p) # removes duplicate occurences in a vector/matrix column
unique(mat)

[1] 1 1 1 1 1 3

[,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1
[4,]    1    1    1
[5,]    1    1    1
[6,]    3    3    3

[1] 1 3

[,1] [,2] [,3]
[1,]    1    1    1
[2,]    3    3    3

In [167]:
system() #?
vector

ERROR: Error in system(): argument "command" is missing, with no default


### Part 2. Matrix manipulation

In [3]:
## 1. Show A and B are invertible

#Generate matrix A and B
A <- matrix(c(1,3,2,4),2,2)
B <- matrix(c(5,7,6,8),2,2)
A
B

#Compute the determinants of A and B
det(A)
det(B)


[,1] [,2]
[1,]    1    2
[2,]    3    4

[,1] [,2]
[1,]    5    6
[2,]    7    8

[1] -2

[1] -2

In [10]:
## 2. Calculate by hand the matrices A−1 and B−1.

A <- matrix(c(1,3,2,4),2,2)
B <- matrix(c(5,7,6,8),2,2)

#Computing inverse for 2*2 matrix
inv_det <- 1/det(A)

inv_A <- matrix[]
inv_A


[1] 2 2

In [13]:
## 3. Use a for loop to create a vector containing the entries in A, 
#     then use the matrix function to convert your vector into the matrix A. Do the same for B.

vect_A <- c(rep(0,4))
vect_B <- c(rep(0,4))

for(i in 1:4){
    vect_A[i] <- i
    vect_B[i] <- i+4
}


A <- matrix(vect_A, 2,2, byrow = TRUE)
B <- matrix(vect_B, 2,2, byrow = TRUE)
A
B

[1] 1 2 3 4

[1] 5 6 7 8

[,1] [,2]
[1,]    1    2
[2,]    3    4

[,1] [,2]
[1,]    5    6
[2,]    7    8

In [23]:
## 4. Create a 2×2 matrix of zeros, then using nested for loops, 
#     loop over individual entries of this matrix filling in the values for A. Do the same for B.

vect_A <- c(1,2,3,4)
vect_B <- c(5,6,7,8)
t <- 1

A <- matrix(c(rep(0,4)),2,2)
B <- matrix(c(rep(0,4)),2,2)

#Loop to fill matrix A
for(i in 1:2){
    for(j in 1:2){
        A[i,j] <- vect_A[t]
        t <- t+1
    }
}

t <- 1
#Loop to fill matrix B
for(i in 1:2){
    for(j in 1:2){
        B[i,j] <- vect_B[t]
        t <- t+1
    }
}

A
B

[,1] [,2]
[1,]    1    2
[2,]    3    4

[,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
## Sorry, I didn't have time to go further... Will finish over the holidays. 

#5. Create vectors a1, a2, b1, b2, corresponding to the columns of A and B. 
#   Use cbind to combine these columns into the matrics A and B.
#6. Use the solve function to calculate the inverse of A and of B.
#7. Use the answer to your above question to calculate A−1A and B−1B